version: "2"
services:
  fpm:
    build: ./php/
    container_name: fpm
    restart: always
    volumes:
      - /data/www:/var/www
      - /data/conf/php/user.ini:/usr/local/etc/php/conf.d/user.ini
    networks:
      - webnet
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  mysql:
    build: ./mariadb/
    container_name: mysql
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webnet
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  # memcached:
  #   build: ./memcache/
  #   container_name: memcached
  #   ports:
  #     - "11211:11211"
  #   networks:
  #     - webnet
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 65535
  #       hard: 65535
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
      - /data/conf/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      - webnet
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
  nginx:
    build: ./nginx/
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/www:/var/www
      - /data/conf/nginx:/etc/nginx/conf.d
      - /data/log/nginx:/var/log/nginx
    depends_on:
      - fpm
    networks:
      - webnet
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
networks:
  webnet:
    driver: bridge
